package modelo;
// Generated 21/05/2016 07:17:23 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ClaseTrabajador generated by hbm2java
 */
@Entity
@Table(name="clase_trabajador"
    ,catalog="proyecto"
)
public class ClaseTrabajador  implements java.io.Serializable {


     private Integer idclaseTrabajador;
     private String descripcion;
     private Set ocupacions = new HashSet(0);

    public ClaseTrabajador() {
    }
    
    public ClaseTrabajador(Integer idclaseTrabajador) {
          this.idclaseTrabajador = idclaseTrabajador;
    }

    public ClaseTrabajador(String descripcion, Set ocupacions) {
       this.descripcion = descripcion;
       this.ocupacions = ocupacions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idclase_trabajador", unique=true, nullable=false)
    public Integer getIdclaseTrabajador() {
        return this.idclaseTrabajador;
    }
    
    public void setIdclaseTrabajador(Integer idclaseTrabajador) {
        this.idclaseTrabajador = idclaseTrabajador;
    }

    
    @Column(name="descripcion", length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="claseTrabajador")
    public Set getOcupacions() {
        return this.ocupacions;
    }
    
    public void setOcupacions(Set ocupacions) {
        this.ocupacions = ocupacions;
    }




}


