package modelo;
// Generated 21/05/2016 07:17:23 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Comunidad generated by hbm2java
 */
@Entity
@Table(name="comunidad"
    ,catalog="proyecto"
)
public class Comunidad  implements java.io.Serializable {


     private Integer idcomunidad;
     private String nombre;
     private String etnia;
     private Set integrantepoblacions = new HashSet(0);
     private Set proyectos = new HashSet(0);

    public Comunidad() {
    }

    public Comunidad(Integer idcomunidad) {
       this.idcomunidad = idcomunidad;
       this.nombre = "";
       this.etnia = "";
    }
   
    
    public Comunidad(String nombre, String etnia, Set integrantepoblacions, Set proyectos) {
       this.nombre = nombre;
       this.etnia = etnia;
       this.integrantepoblacions = integrantepoblacions;
       this.proyectos = proyectos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idcomunidad", unique=true, nullable=false)
    public Integer getIdcomunidad() {
        return this.idcomunidad;
    }
    
    public void setIdcomunidad(Integer idcomunidad) {
        this.idcomunidad = idcomunidad;
    }

    
    @Column(name="nombre", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="etnia", length=45)
    public String getEtnia() {
        return this.etnia;
    }
    
    public void setEtnia(String etnia) {
        this.etnia = etnia;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="comunidad")
    public Set getIntegrantepoblacions() {
        return this.integrantepoblacions;
    }
    
    public void setIntegrantepoblacions(Set integrantepoblacions) {
        this.integrantepoblacions = integrantepoblacions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="comunidad")
    public Set getProyectos() {
        return this.proyectos;
    }
    
    public void setProyectos(Set proyectos) {
        this.proyectos = proyectos;
    }

    @Override
    public String toString() {
        return "Comunidad{" + "idcomunidad=" + idcomunidad + ", nombre=" + nombre + ", etnia=" + etnia + ", integrantepoblacions=" + integrantepoblacions + ", proyectos=" + proyectos + '}';
    }


}


