package modelo;
// Generated 21/05/2016 07:17:23 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Comunidad generated by hbm2java
 */


public class Evaluacion  implements java.io.Serializable {


     private Integer eva;
     private String Titulo;
     

    public Evaluacion() {
    }

    public Evaluacion(Integer eva, String Titulo) {
        this.eva = eva;
        this.Titulo = Titulo;
    }
    
    

    public Integer getEva() {
        return eva;
    }

    public void setEva(Integer eva) {
        this.eva = eva;
    }

    public String getTitulo() {
        return Titulo;
    }

    public void setTitulo(String Titulo) {
        this.Titulo = Titulo;
    }

  
   
   
}


