package modelo;
// Generated 21/05/2016 07:17:23 PM by Hibernate Tools 3.6.0


import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Integrantepoblacion generated by hbm2java
 */
@Entity
@Table(name="integrantepoblacion"
    ,catalog="proyecto"
)
public class Integrantepoblacion  implements java.io.Serializable {


     private Integer idIntegrante;
     private Comunidad comunidad;
     private String nombres;
     private String apellidos;
     private String fechaNacimiento;
     private Set representantes = new HashSet(0);
     private Date fecha_select;
     
     

    public Integrantepoblacion() {
    }

	
    public Integrantepoblacion(Comunidad comunidad) {
        this.comunidad = comunidad;
    }
    
    public Integrantepoblacion(Integer idIntegrante,String nombres, String apellidos, String fechaNacimiento) {
       this.idIntegrante = idIntegrante;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.fechaNacimiento = fechaNacimiento;
    }
    
    
    public Integrantepoblacion(Comunidad comunidad, String nombres, String apellidos, String fechaNacimiento, Set representantes) {
         this.comunidad = comunidad;
         this.nombres = nombres;
         this.apellidos = apellidos;
         this.fechaNacimiento = fechaNacimiento;
         this.representantes = representantes;
         try {    
             SimpleDateFormat format = new SimpleDateFormat("dd-MM-yyyy");
             this.fecha_select = format.parse(fechaNacimiento);
         } catch (ParseException ex) {
             Logger.getLogger(Integrantepoblacion.class.getName()).log(Level.SEVERE, null, ex);
         }
       
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idIntegrante", unique=true, nullable=false)
    public Integer getIdIntegrante() {
        return this.idIntegrante;
    }
    
    public void setIdIntegrante(Integer idIntegrante) {
        this.idIntegrante = idIntegrante;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="comunidad_idcomunidad", nullable=false)
    public Comunidad getComunidad() {
        return this.comunidad;
    }
    
    public void setComunidad(Comunidad comunidad) {
        this.comunidad = comunidad;
    }

    
    @Column(name="nombres", length=45)
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    
    @Column(name="apellidos", length=45)
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    
    @Column(name="fechaNacimiento", length=45)
    public String getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(String fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="integrantepoblacion")
    public Set getRepresentantes() {
        return this.representantes;
    }
    
    public void setRepresentantes(Set representantes) {
        this.representantes = representantes;
    }

    public Date getFecha_select() {
        return fecha_select;
    }

    public void setFecha_select(Date fecha_select) {
        this.fecha_select = fecha_select;
    }




}


