package modelo;
// Generated 21/05/2016 07:17:23 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Objetivo generated by hbm2java
 */
@Entity
@Table(name="objetivo"
    ,catalog="proyecto"
)
public class Objetivo  implements java.io.Serializable {


     private Integer idobjetivo;
     private Proyecto proyecto;
     private String descripcion;
     private Boolean cumplimiento;

    public Objetivo() {
    }

	
    public Objetivo(Proyecto proyecto) {
        this.proyecto = proyecto;
    }
     
    public Objetivo(String descripcion, Boolean cumplimiento) {
       this.descripcion = descripcion;
       this.cumplimiento = cumplimiento;
    }
    
    public Objetivo(Proyecto proyecto, String descripcion, Boolean cumplimiento) {
       this.proyecto = proyecto;
       this.descripcion = descripcion;
       this.cumplimiento = cumplimiento;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idobjetivo", unique=true, nullable=false)
    public Integer getIdobjetivo() {
        return this.idobjetivo;
    }
    
    public void setIdobjetivo(Integer idobjetivo) {
        this.idobjetivo = idobjetivo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Proyecto_idProyecto", nullable=false)
    public Proyecto getProyecto() {
        return this.proyecto;
    }
    
    public void setProyecto(Proyecto proyecto) {
        this.proyecto = proyecto;
    }

    
    @Column(name="descripcion", length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="cumplimiento")
    public Boolean getCumplimiento() {
        return this.cumplimiento;
    }
    
    public void setCumplimiento(Boolean cumplimiento) {
        this.cumplimiento = cumplimiento;
    }




}


