package modelo;
// Generated 21/05/2016 07:17:23 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProyectoTrabajador generated by hbm2java
 */
@Entity
@Table(name="proyecto_trabajador"
    ,catalog="proyecto"
)
public class ProyectoTrabajador  implements java.io.Serializable {


     private Integer idProyectoTrabajador;
     private Trabajador trabajador;
     private Proyecto proyecto;
     private Set representanteProyectos = new HashSet(0);
     private Set tareases = new HashSet(0);

    public ProyectoTrabajador() {
    }

	
    public ProyectoTrabajador(Trabajador trabajador, Proyecto proyecto) {
        this.trabajador = trabajador;
        this.proyecto = proyecto;
    }
    public ProyectoTrabajador(Trabajador trabajador, Proyecto proyecto, Set representanteProyectos, Set tareases) {
       this.trabajador = trabajador;
       this.proyecto = proyecto;
       this.representanteProyectos = representanteProyectos;
       this.tareases = tareases;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idProyecto_trabajador", unique=true, nullable=false)
    public Integer getIdProyectoTrabajador() {
        return this.idProyectoTrabajador;
    }
    
    public void setIdProyectoTrabajador(Integer idProyectoTrabajador) {
        this.idProyectoTrabajador = idProyectoTrabajador;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="trabajador_idtrabajador", nullable=false)
    public Trabajador getTrabajador() {
        return this.trabajador;
    }
    
    public void setTrabajador(Trabajador trabajador) {
        this.trabajador = trabajador;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Proyecto_idProyecto", nullable=false)
    public Proyecto getProyecto() {
        return this.proyecto;
    }
    
    public void setProyecto(Proyecto proyecto) {
        this.proyecto = proyecto;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="proyectoTrabajador")
    public Set getRepresentanteProyectos() {
        return this.representanteProyectos;
    }
    
    public void setRepresentanteProyectos(Set representanteProyectos) {
        this.representanteProyectos = representanteProyectos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="proyectoTrabajador")
    public Set getTareases() {
        return this.tareases;
    }
    
    public void setTareases(Set tareases) {
        this.tareases = tareases;
    }




}


