package modelo;
// Generated 21/05/2016 07:17:23 PM by Hibernate Tools 3.6.0


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RepresentanteProyecto generated by hbm2java
 */
@Entity
@Table(name="representante_proyecto"
    ,catalog="proyecto"
)
public class RepresentanteProyecto  implements java.io.Serializable {


     private RepresentanteProyectoId id;
     private ProyectoTrabajador proyectoTrabajador;

    public RepresentanteProyecto() {
    }

    public RepresentanteProyecto(RepresentanteProyectoId id, ProyectoTrabajador proyectoTrabajador) {
       this.id = id;
       this.proyectoTrabajador = proyectoTrabajador;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idRepresentanteProyecto", column=@Column(name="idRepresentante_proyecto", nullable=false) ), 
        @AttributeOverride(name="proyectoTrabajadorIdProyectoTrabajador", column=@Column(name="Proyecto_trabajador_idProyecto_trabajador", nullable=false) ) } )
    public RepresentanteProyectoId getId() {
        return this.id;
    }
    
    public void setId(RepresentanteProyectoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Proyecto_trabajador_idProyecto_trabajador", nullable=false, insertable=false, updatable=false)
    public ProyectoTrabajador getProyectoTrabajador() {
        return this.proyectoTrabajador;
    }
    
    public void setProyectoTrabajador(ProyectoTrabajador proyectoTrabajador) {
        this.proyectoTrabajador = proyectoTrabajador;
    }




}


