package modelo;
// Generated 21/05/2016 07:17:23 PM by Hibernate Tools 3.6.0


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Representante generated by hbm2java
 */
@Entity
@Table(name="representante"
    ,catalog="proyecto"
)
public class Representante  implements java.io.Serializable {


     private RepresentanteId id;
     private Integrantepoblacion integrantepoblacion;
     private String telefono;
     private String direccion;
     private String email;

    public Representante() {
    }

	
    public Representante(RepresentanteId id, Integrantepoblacion integrantepoblacion) {
        this.id = id;
        this.integrantepoblacion = integrantepoblacion;
    }
    public Representante(RepresentanteId id, Integrantepoblacion integrantepoblacion, String telefono, String direccion, String email) {
       this.id = id;
       this.integrantepoblacion = integrantepoblacion;
       this.telefono = telefono;
       this.direccion = direccion;
       this.email = email;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idrepresentante", column=@Column(name="idrepresentante", nullable=false) ), 
        @AttributeOverride(name="integrantePoblacionIdIntegrante", column=@Column(name="integrantePoblacion_idIntegrante", nullable=false) ) } )
    public RepresentanteId getId() {
        return this.id;
    }
    
    public void setId(RepresentanteId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="integrantePoblacion_idIntegrante", nullable=false, insertable=false, updatable=false)
    public Integrantepoblacion getIntegrantepoblacion() {
        return this.integrantepoblacion;
    }
    
    public void setIntegrantepoblacion(Integrantepoblacion integrantepoblacion) {
        this.integrantepoblacion = integrantepoblacion;
    }

    
    @Column(name="telefono", length=45)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="direccion", length=45)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="email", length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


