package modelo;
// Generated 21/05/2016 07:17:23 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RepresentanteId generated by hbm2java
 */
@Embeddable
public class RepresentanteId  implements java.io.Serializable {


     private int idrepresentante;
     private int integrantePoblacionIdIntegrante;

    public RepresentanteId() {
    }

    public RepresentanteId(int idrepresentante, int integrantePoblacionIdIntegrante) {
       this.idrepresentante = idrepresentante;
       this.integrantePoblacionIdIntegrante = integrantePoblacionIdIntegrante;
    }
   


    @Column(name="idrepresentante", nullable=false)
    public int getIdrepresentante() {
        return this.idrepresentante;
    }
    
    public void setIdrepresentante(int idrepresentante) {
        this.idrepresentante = idrepresentante;
    }


    @Column(name="integrantePoblacion_idIntegrante", nullable=false)
    public int getIntegrantePoblacionIdIntegrante() {
        return this.integrantePoblacionIdIntegrante;
    }
    
    public void setIntegrantePoblacionIdIntegrante(int integrantePoblacionIdIntegrante) {
        this.integrantePoblacionIdIntegrante = integrantePoblacionIdIntegrante;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RepresentanteId) ) return false;
		 RepresentanteId castOther = ( RepresentanteId ) other; 
         
		 return (this.getIdrepresentante()==castOther.getIdrepresentante())
 && (this.getIntegrantePoblacionIdIntegrante()==castOther.getIntegrantePoblacionIdIntegrante());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdrepresentante();
         result = 37 * result + this.getIntegrantePoblacionIdIntegrante();
         return result;
   }   


}


