package modelo;
// Generated 21/05/2016 07:17:23 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RepresentanteProyectoId generated by hbm2java
 */
@Embeddable
public class RepresentanteProyectoId  implements java.io.Serializable {


     private int idRepresentanteProyecto;
     private int proyectoTrabajadorIdProyectoTrabajador;

    public RepresentanteProyectoId() {
    }

    public RepresentanteProyectoId(int idRepresentanteProyecto, int proyectoTrabajadorIdProyectoTrabajador) {
       this.idRepresentanteProyecto = idRepresentanteProyecto;
       this.proyectoTrabajadorIdProyectoTrabajador = proyectoTrabajadorIdProyectoTrabajador;
    }
   


    @Column(name="idRepresentante_proyecto", nullable=false)
    public int getIdRepresentanteProyecto() {
        return this.idRepresentanteProyecto;
    }
    
    public void setIdRepresentanteProyecto(int idRepresentanteProyecto) {
        this.idRepresentanteProyecto = idRepresentanteProyecto;
    }


    @Column(name="Proyecto_trabajador_idProyecto_trabajador", nullable=false)
    public int getProyectoTrabajadorIdProyectoTrabajador() {
        return this.proyectoTrabajadorIdProyectoTrabajador;
    }
    
    public void setProyectoTrabajadorIdProyectoTrabajador(int proyectoTrabajadorIdProyectoTrabajador) {
        this.proyectoTrabajadorIdProyectoTrabajador = proyectoTrabajadorIdProyectoTrabajador;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RepresentanteProyectoId) ) return false;
		 RepresentanteProyectoId castOther = ( RepresentanteProyectoId ) other; 
         
		 return (this.getIdRepresentanteProyecto()==castOther.getIdRepresentanteProyecto())
 && (this.getProyectoTrabajadorIdProyectoTrabajador()==castOther.getProyectoTrabajadorIdProyectoTrabajador());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdRepresentanteProyecto();
         result = 37 * result + this.getProyectoTrabajadorIdProyectoTrabajador();
         return result;
   }   


}


