package modelo;
// Generated 21/05/2016 07:17:23 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Temas generated by hbm2java
 */
@Entity
@Table(name="temas"
    ,catalog="proyecto"
)
public class Temas  implements java.io.Serializable {


     private Integer idtemas;
     private String descripcion;
     private Set proyectos = new HashSet(0);

    public Temas() {
    }

    public Temas(Integer idtema) {
       this.idtemas = idtema;
       this.descripcion = "";
    }
    
    public Temas(String descripcion, Set proyectos) {
       this.descripcion = descripcion;
       this.proyectos = proyectos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idtemas", unique=true, nullable=false)
    public Integer getIdtemas() {
        return this.idtemas;
    }
    
    public void setIdtemas(Integer idtemas) {
        this.idtemas = idtemas;
    }

    
    @Column(name="descripcion", length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="temas")
    public Set getProyectos() {
        return this.proyectos;
    }
    
    public void setProyectos(Set proyectos) {
        this.proyectos = proyectos;
    }

    @Override
    public String toString() {
        return "Temas{" + "idtemas=" + idtemas + ", descripcion=" + descripcion + ", proyectos=" + proyectos + '}';
    }

}


